### ISSUE TITLE
Error in creating Recipient account 

### ISSUE THREAD

**Issue by spx21** [trolley/dotnet-sdk#2]
Hi
When I tried to create recipient account and set the value primary to true.
I got this response. 
already tried different values but if gives mi exception unauthorized
{
  "ok": false,
  "errors": [
    {
      "code": "invalid_field",
      "message": "must be boolean got string",
      "field": "isPrimary"
    }
  ]
}

**Comment by koblas** [comment]
This should now be fixed in the recently merged PR.
