### ISSUE TITLE
Unable to Create Recipient Account using type = "paypal"

### ISSUE THREAD

**Issue by Vignesh-pikcha** [trolley/dotnet-sdk#5]
When creating the Recipient Account for each recipient and providing all required files with the payment Method type as "paypal", It returns the Email address is null.

the values which I send to API
id = "R-12345",
type = "paypal",
primary = "true",
emailAddress = "example@gmail.com"

response:
Pikcha.PaymentRails.Exceptions.MalformedUrlException: 
{"ok":false,
"errors":[{"code":"empty_field",
               "message":"Expected to have a non-null or non-empty value",
                "field":"emailAddress"}]
}

**Comment by koblas** [comment]
@fronugget 

Can you look at this line, looks like it's serialized wrong

https://github.com/PaymentRails/paymentrails_dotnet/blob/ce510689d57a28d07c12f15cea0208ee82824446/paymentrails/Types/RecipientAccount.cs#L174

**Comment by fronugget** [comment]
Repo updated with a fix for this issue
