### ISSUE TITLE
String.Format needs conversion help

### ISSUE THREAD

**Issue by fronugget** [trolley/dotnet-sdk#6]
use something like this to control the conversion: String.Format("{0:0.00}", double)

apparent in payments.

**Comment by kinzdesign** [comment]
Until this is fixed, it is impossible to payout a multiple of ten cents that isn't an even dollar amount using the SDK. e.g. paying $10 works, paying $10.11 works, but $10.10 fails.

**Comment by Aman-Aalam** [comment]
Fixed with v1.0.11, awaiting release
