### ISSUE TITLE
Accented characters erroring out

### ISSUE THREAD

**Issue by fronugget** [trolley/dotnet-sdk#7]
When supplying the following to create a new recipient, I got an invalid hash error:

new Recipient("individual", vendor.Email.Trim(), “Eva Morón”, “Eva”, “Morón”, null, vendor.Id.ToString(), null, vendor.TimeZone, "en");

It seems to hang on Morón with the accented “e”. But if I convert from Morón to ASCII (Moron), then it works.

**Comment by Vignesh-pikcha** [comment]
Even I'm facing the same issue with accented characters:

**Input:**

`{
    "UserId" : "001",
    "Id" : "",
    "Type": "individual",
    "Name" : "John Wick",
    "FirstName" : "John",
    "LastName" : "Wick",
    "Email" : "jWick@gmail.com",
    "Passport" : "",
    "Dob" : "",
    "Message" : "",
    "Address" : 
    {
        "Street1" : "aleja Pracy",
        "Street2" : "",
        "City" : "Wrocław",
        "Region" : "Dolnośląskie",
        "PostalCode" : "53-231",
        "Country" : "PL",
        "Phone" : ""
    }
}`

**Output:**

`"status": "{\"ok\":false,\"errors\":[{\"code\":\"invalid_api_key\",\"message\":\"Invalid token: bad hash\"}]}",`
